### ISSUE TITLE
Cannot clone K-Search

### ISSUE THREAD

**Issue by stevanmarjanovic** [k-box/k-search#6]
I have applied to contribute to K-Box, and one of the dependents in dev environment is K-Search. But, when I try to install it as instructed in the README.md:
```bash
git clone git@git.klink.asia:main/k-search.git --recursive
```
 I get the following error.
```
Cloning into 'k-search'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
Could you guide me to what I'm missing?

**Comment by avvertix** [comment]
Seems that the URL in the readme points you to use SSH for cloning from an internal repository. You could clone this (https://github.com/k-box/k-search/) repository instead. If you need to contribute only to the K-Box there is the possibility to use [Docker](https://www.docker.com/) to resolve both K-Search and K-Search Engine dependencies, as [suggested here](https://github.com/k-box/k-box/blob/master/docs/developer/developer-installation.md#required-services). 

Indeed I will update the readme of this repository as soon as possible.

**Comment by avvertix** [comment]
The documentation has been updated
